apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: ml-api
spec:
  selector:
    app: api
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080  # Accesible en http://<IP>:30080

