apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: ml-api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: python:3.10
          command: ["/bin/bash", "-c"]
          args:
            - |
              pip install --no-cache-dir -r /app/requirements.txt && \
              uvicorn app.main:app --host 0.0.0.0 --port 8000
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: app-volume
              mountPath: /app
      volumes:
        - name: app-volume
          hostPath:
            path: /home/estudiante/Documents/MLOPS/MLOPS_Grupo_5/Taller_CI_CD/api/app
            type: Directory

