apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'fastapi-metrics'
        static_configs:
          - targets: ['10.43.101.195:30190']
        metrics_path: '/metrics'
