apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadtester
  namespace: ml-api
  labels:
    app: loadtester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtester
  template:
    metadata:
      labels:
        app: loadtester
    spec:
      containers:
        - name: loadtester
          image: python:3.10
          command: ["/bin/bash", "-c"]
          args:
            - |
              pip install --no-cache-dir -r /load/requirements.txt && \
              python /load/main.py && \
              sleep 3600
          volumeMounts:
            - name: script-volume
              mountPath: /load
      volumes:
        - name: script-volume
          hostPath:
            path: /home/estudiante/Documents/MLOPS/MLOPS_Grupo_5/Taller_CI_CD/loadtester
            type: Directory

