apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadtester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtester
  template:
    metadata:
      labels:
        app: loadtester
    spec:
      containers:
        - name: loadtester
          image: loadtester:latest
          imagePullPolicy: Never
          command: ["python"]
          args: ["main.py"]
          volumeMounts:
            - name: loadtester-volume
              mountPath: /app
      volumes:
        - name: loadtester-volume
          hostPath:
            path: /home/estudiante/Documents/MLOPS/MLOPS_Grupo_5/Taller_CI_CD/loadtester
            type: Directory

