apiVersion: v1
kind: Service
metadata:
  name: postgres-airflow
  namespace: mlops-final
spec:
  selector:
    app: postgres-airflow
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP

