apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-airflow
  namespace: mlops-final  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-airflow
  template:
    metadata:
      labels:
        app: postgres-airflow
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admingrupo5
            - name: POSTGRES_DB
              value: airflow
          volumeMounts:
            - name: postgres-airflow-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-airflow-storage
          persistentVolumeClaim:
            claimName: postgres-airflow-pvc

