apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: python:3.10-slim
          workingDir: /app
          command: ["bash", "-c"]
          args:
            - |
              pip install --no-cache-dir -r requirements.txt && \
              streamlit run app.py --server.port=8503 --server.address=0.0.0.0
          env:
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow:5000
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio:9000
            - name: AWS_ACCESS_KEY_ID
              value: admin
            - name: AWS_SECRET_ACCESS_KEY
              value: supersecret
          ports:
            - containerPort: 8503
          volumeMounts:
            - name: streamlit-code
              mountPath: /app
      volumes:
        - name: streamlit-code
          hostPath:
            path: /home/estudiante/Documents/MLOPS/MLOPS_Grupo_5/Proyecto_3_Grupo_5/streamlit
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit
spec:
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 8503
      targetPort: 8503
  type: NodePort

