apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadtester
  namespace: mlops-final
  labels:
    app: loadtester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtester
  template:
    metadata:
      labels:
        app: loadtester
    spec:
      containers:
        - name: loadtester
          image: rubenromero800/loadtester:v4
          ports:
            - containerPort: 8089  # si usas locust UI

