apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: mlops-final
spec:
  selector:
    app: airflow-webserver
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080

