apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: mlops-final
spec:
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      nodePort: 30090
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: 30091
  type: NodePort

