apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-data
  namespace: mlops-final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-data
  template:
    metadata:
      labels:
        app: postgres-data
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admingrupo5
            - name: POSTGRES_DB
              value: data_db
          volumeMounts:
            - name: postgres-data-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data-storage
          persistentVolumeClaim:
            claimName: postgres-data-pvc

