apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: mlops-final
  labels:
    app: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      nodeSelector:
        kubernetes.io/hostname: noam24
      containers:
        - name: fastapi
          image: rubenromero800/fastapi:v6
          ports:
            - containerPort: 8000
          env:
            - name: MLFLOW_TRACKING_URI
              value: http://10.43.101.195:30958
            - name: DATABASE_URL
              value: postgresql://admin:admingrupo5@postgres-mlflow:5432/data_db
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://10.43.101.195:30090
            - name: AWS_ACCESS_KEY_ID
              value: admin
            - name: AWS_SECRET_ACCESS_KEY
              value: supersecret

