apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: mlops-final
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30190
  type: NodePort

