apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
        - name: webserver
          image: apache/airflow:2.7.3-python3.10
          command: ["bash", "-c"]
          args:
            - |
              pip install --no-cache-dir --break-system-packages -r /airflow/requirements.txt && \
              airflow db upgrade && \
              airflow users create \
                --username airflow --password airflow \
                --firstname Air --lastname Flow \
                --role Admin --email airflow@example.com && \
              airflow webserver
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: airflow-config
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
            - name: airflow-folder
              mountPath: /airflow
            - name: logs
              mountPath: /opt/airflow/logs
            - name: data
              mountPath: /opt/airflow/data
      volumes:
        - name: dags
          hostPath:
            path: /home/estudiante/Documents/MLOPS/MLOPS_Grupo_5/Proyecto_3_Grupo_5/airflow/dags
        - name: airflow-folder
          hostPath:
            path: /home/estudiante/Documents/MLOPS/MLOPS_Grupo_5/Proyecto_3_Grupo_5/airflow
        - name: logs
          hostPath:
            path: /home/estudiante/Documents/MLOPS/MLOPS_Grupo_5/Proyecto_3_Grupo_5/airflow/logs
        - name: data
          hostPath:
            path: /home/estudiante/Documents/MLOPS/MLOPS_Grupo_5/Proyecto_3_Grupo_5/airflow/data

