apiVersion: v1
kind: Service
metadata:
  name: locust-master
spec:
  selector:
    app: locust
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
      nodePort: 30040  # Puedes cambiarlo si está ocupado
  type: NodePort

