apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
  template:
    metadata:
      labels:
        app: locust
    spec:
      containers:
        - name: locust-master
          image: locustio/locust
          command: ["locust", "-f", "/mnt/locust/locustfile.py", "--host", "http://10.43.101.195:30190"]
          ports:
            - containerPort: 8089
          volumeMounts:
            - name: locustfile-volume
              mountPath: /mnt/locust
      volumes:
        - name: locustfile-volume
          configMap:
            name: locustfile

