apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: mlops-final
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30041

