apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: mlops-final
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'fastapi-metrics'
        static_configs:
          - targets: ['fastapi.mlops-final.svc.cluster.local:80']
        metrics_path: '/metrics'

