apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlops-final
spec:
  selector:
    app: mlflow
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort  # Puedes cambiar a LoadBalancer si usas MetalLB

