name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'MLOPS_Grupo_5/Proyecto_Final_Grupo_5/fastapi/**'
      - 'MLOPS_Grupo_5/Proyecto_Final_Grupo_5/loadtester/**'
      - 'MLOPS_Grupo_5/Proyecto_Final_Grupo_5/streamlit/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [fastapi, loadtester, streamlit]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set DockerHub credentials
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u rubenromero800 --password-stdin

      - name: Determine next version tag
        id: version
        run: |
          NAME=${{ matrix.component }}
          IMAGE="rubenromero800/$NAME"
          CURRENT=$(curl -s "https://hub.docker.com/v2/repositories/$IMAGE/tags" | jq -r '.results[].name' | grep '^v' | sed 's/v//' | sort -nr | head -n1)
          NEXT=$((CURRENT + 1))
          echo "next_version=v$NEXT" >> $GITHUB_OUTPUT

      - name: Build and tag image
        run: |
          cd MLOPS_Grupo_5/Proyecto_Final_Grupo_5/${{ matrix.component }}
          docker build -t rubenromero800/${{ matrix.component }}:${{ steps.version.outputs.next_version }} .

      - name: Push image
        run: docker push rubenromero800/${{ matrix.component }}:${{ steps.version.outputs.next_version }}
