name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'MLOPS_Grupo_5/Proyecto_Final_Grupo_5/fastapi/**'
      - 'MLOPS_Grupo_5/Proyecto_Final_Grupo_5/loadtester/**'
      - 'MLOPS_Grupo_5/Proyecto_Final_Grupo_5/streamlit/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: docker.io
      USERNAME: rubenromero800
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push FastAPI image
        uses: docker/build-push-action@v5
        with:
          context: ./MLOPS_Grupo_5/Proyecto_Final_Grupo_5/fastapi
          push: true
          tags: ${{ env.USERNAME }}/fastapi:latest,${{ env.USERNAME }}/fastapi:${{ github.sha }}

      - name: Build and push LoadTester image
        uses: docker/build-push-action@v5
        with:
          context: ./MLOPS_Grupo_5/Proyecto_Final_Grupo_5/loadtester
          push: true
          tags: ${{ env.USERNAME }}/loadtester:latest,${{ env.USERNAME }}/loadtester:${{ github.sha }}

      - name: Build and push Streamlit image
        uses: docker/build-push-action@v5
        with:
          context: ./MLOPS_Grupo_5/Proyecto_Final_Grupo_5/streamlit
          push: true
          tags: ${{ env.USERNAME }}/streamlit:latest,${{ env.USERNAME }}/streamlit:${{ github.sha }}
