name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  train-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        working-directory: Taller_CI_CD/api
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Train model
        working-directory: Taller_CI_CD
        run: python api/train_model.py

      - name: Commit trained model artifacts
        working-directory: Taller_CI_CD
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add api/app/model.pkl api/app/label_encoder.pkl
          git commit -m "Update trained model artifacts" || echo "No changes to commit"
          git push
